apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: anotherclass-222-qa
commonLabels:
  version: 1.0.0
resources:
  - ../../base
patches:
  - path: configmap.yaml
  - path: deployment-spec.yaml
  - path: deployment-ver.yaml
  - path: secret.yaml
  - path: service.yaml