apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tester-2222
spec:
  template:
    spec:
      containers:
        - name: api-tester-2222
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"