apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: anotherclass-222-dev
commonLabels:
  version: 2.0.0
resources:
  - ../../base
patches:
  - path: configmap.yaml
  - path: deployment-spec.yaml
  - path: deployment-ver.yaml
  - path: secret.yaml
  - path: service.yaml