apiVersion: v1
kind: Secret
metadata:
  name: api-tester-2222-postgresql
stringData:
  postgresql-info.yaml: |
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://postgresql:5431"
    username: "dev"
    password: "dev123"